ROUNDS_NUMBER = 5

LLM_RETRY_LIMIT = 1

CALIBRATION_KEY = "c"

PROMPT_FILE_PATH = "LLM/prompt.txt"
KEYPOINTS_FILE_PATH = "ui/keypoints.json"
TEST_RESPONSE_FILE_PATH = "mocks/mocked_response.txt"

CLICK_DURATION_IN_SECONDS = 0.5
POST_CLICK_DELAY_IN_SECONDS = 1
PRE_ROUND_DELAY_IN_SECONDS = 1
POST_ROUND_DELAY_IN_SECONDS = 2
POST_CALIBRATION_DELAY_IN_SECONDS = 3