ROUNDS_NUMBER = 5

LLM_RETRY_LIMIT = 1

START_GAME_KEY = "g"
CALIBRATION_KEY = "c"

KEYPOINTS_FILE = "ui/keypoints.json"
CALIBRATION_MAP_FILE = "ui/calibration_map.txt"
TEST_RESPONSE_FILE = "mocks/mocked_response.txt"

AZURE_STORAGE_CONTAINER_NAME = "screenshots"

CLICK_DURATION = 0.5
POST_CLICK_DELAY = 1
PRE_ROUND_DELAY = 1
POST_ROUND_DELAY = 2
POST_CALIBRATION_DELAY = 3